DROP TABLE IF EXISTS `%PREFIX%_structure`;

CREATE TABLE `%PREFIX%_structure` (
  `id` varchar(255) NOT NULL,
  `parent_id` varchar(255) DEFAULT NULL,
  `caption` text,
  `order_number` int(2) DEFAULT NULL,
  `properties` text,
  `serialize` text,
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`),
  KEY `caption` (`caption`(255)),
  KEY `order_number` (`order_number`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Структура страниц сайта';
INSERT INTO `%PREFIX%_structure` VALUES ('index', null, 'Главная страница', null, 'a:10:{s:7:\"caption\";s:31:\"Главная страница\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:31:\"Главная страница\";s:8:\"template\";s:21:\"design/template1.html\";s:7:\"visible\";s:4:\"true\";s:16:\"waysite1_visible\";s:4:\"true\";s:16:\"mapsite1_visible\";s:4:\"true\";s:13:\"menu1_visible\";s:4:\"true\";s:9:\"only_auth\";b:0;s:15:\"link_other_page\";s:0:\"\";}', 'a:7:{s:5:\"title\";a:3:{s:6:\"id_mod\";s:6:\"kernel\";s:9:\"id_action\";s:1:\"2\";s:3:\"run\";a:2:{s:4:\"name\";s:19:\"priv_page_title_get\";s:5:\"param\";s:6:\"a:0:{}\";}}s:3:\"way\";a:3:{s:6:\"id_mod\";s:8:\"waysite1\";s:9:\"id_action\";s:1:\"9\";s:3:\"run\";a:2:{s:4:\"name\";s:16:\"pub_show_waysite\";s:5:\"param\";s:68:\"a:1:{s:8:\"template\";s:39:\"modules/waysite/templates_user/way.html\";}\";}}s:6:\"search\";a:3:{s:6:\"id_mod\";s:7:\"search1\";s:9:\"id_action\";s:2:\"34\";s:3:\"run\";a:2:{s:4:\"name\";s:18:\"pub_show_only_form\";s:5:\"param\";s:75:\"a:1:{s:8:\"template\";s:46:\"modules/search/templates_user//form_small.html\";}\";}}s:14:\"basket_sticker\";a:3:{s:6:\"id_mod\";s:8:\"catalog1\";s:9:\"id_action\";s:2:\"38\";s:3:\"run\";a:2:{s:4:\"name\";s:29:\"pub_catalog_show_basket_label\";s:5:\"param\";s:193:\"a:2:{s:22:\"basket_label_empty_tpl\";s:57:\"modules/catalog/templates_user//basket_sticker_empty.html\";s:25:\"basket_label_notempty_tpl\";s:51:\"modules/catalog/templates_user//basket_sticker.html\";}\";}}s:7:\"content\";a:3:{s:6:\"id_mod\";s:6:\"kernel\";s:9:\"id_action\";s:1:\"1\";s:3:\"run\";a:2:{s:4:\"name\";s:22:\"priv_html_editor_start\";s:5:\"param\";s:6:\"a:0:{}\";}}s:4:\"menu\";a:3:{s:6:\"id_mod\";s:5:\"menu1\";s:9:\"id_action\";s:2:\"17\";s:3:\"run\";a:2:{s:4:\"name\";s:13:\"pub_show_menu\";s:5:\"param\";s:168:\"a:4:{s:13:\"id_page_start\";s:5:\"index\";s:17:\"count_level_start\";s:1:\"1\";s:16:\"count_level_show\";s:1:\"3\";s:8:\"template\";s:41:\"modules/menu/templates_user/extended.html\";}\";}}s:5:\"lenta\";a:3:{s:6:\"id_mod\";s:6:\"newsi1\";s:9:\"id_action\";s:2:\"15\";s:3:\"run\";a:2:{s:4:\"name\";s:14:\"pub_show_lenta\";s:5:\"param\";s:136:\"a:4:{s:8:\"template\";s:39:\"modules/newsi/templates_user/lenta.html\";s:5:\"limit\";s:2:\"10\";s:4:\"type\";s:7:\"default\";s:4:\"page\";s:4:\"news\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('about', 'index', 'О компании', '1', 'a:6:{s:7:\"caption\";s:19:\"О компании\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:19:\"О компании\";s:8:\"template\";s:21:\"design/template1.html\";s:9:\"only_auth\";s:0:\"\";s:15:\"link_other_page\";s:0:\"\";}', 'a:2:{s:3:\"way\";a:3:{s:6:\"id_mod\";s:8:\"waysite1\";s:9:\"id_action\";s:1:\"9\";s:3:\"run\";a:2:{s:4:\"name\";s:16:\"pub_show_waysite\";s:5:\"param\";s:68:\"a:1:{s:8:\"template\";s:39:\"modules/waysite/templates_user/way.html\";}\";}}s:7:\"content\";a:3:{s:6:\"id_mod\";s:6:\"kernel\";s:9:\"id_action\";s:1:\"1\";s:3:\"run\";a:2:{s:4:\"name\";s:22:\"priv_html_editor_start\";s:5:\"param\";s:6:\"a:0:{}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('contacts', 'index', 'Контакты', '4', 'a:6:{s:7:\"caption\";s:16:\"Контакты\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:16:\"Контакты\";s:8:\"template\";s:21:\"design/template1.html\";s:9:\"only_auth\";s:0:\"\";s:15:\"link_other_page\";s:0:\"\";}', 'a:2:{s:3:\"way\";a:3:{s:6:\"id_mod\";s:8:\"waysite1\";s:9:\"id_action\";s:1:\"9\";s:3:\"run\";a:2:{s:4:\"name\";s:16:\"pub_show_waysite\";s:5:\"param\";s:68:\"a:1:{s:8:\"template\";s:39:\"modules/waysite/templates_user/way.html\";}\";}}s:7:\"content\";a:3:{s:6:\"id_mod\";s:6:\"kernel\";s:9:\"id_action\";s:1:\"1\";s:3:\"run\";a:2:{s:4:\"name\";s:22:\"priv_html_editor_start\";s:5:\"param\";s:6:\"a:0:{}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('photos', 'index', 'Фотогалерея', '6', 'a:6:{s:7:\"caption\";s:22:\"Фотогалерея\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:22:\"Фотогалерея\";s:9:\"only_auth\";s:0:\"\";s:8:\"template\";s:21:\"design/template2.html\";s:15:\"link_other_page\";s:0:\"\";}', 'a:1:{s:7:"content";a:3:{s:6:"id_mod";s:8:"catalog2";s:9:"id_action";s:2:"41";s:3:"run";a:2:{s:4:"name";s:40:"pub_catalog_show_inner_selection_results";s:5:"param";s:61:"a:1:{s:32:"catalog_inner_selection_stringid";s:8:"allphoto";}";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('mapsite', 'index', 'Карта сайта', '5', 'a:7:{s:7:\"caption\";s:21:\"Карта сайта\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:21:\"Карта сайта\";s:8:\"template\";s:21:\"design/template2.html\";s:9:\"only_auth\";s:0:\"\";s:15:\"link_other_page\";s:0:\"\";s:16:\"mapsite1_visible\";s:5:\"false\";}', 'a:2:{s:3:\"way\";a:3:{s:6:\"id_mod\";s:8:\"waysite1\";s:9:\"id_action\";s:1:\"9\";s:3:\"run\";a:2:{s:4:\"name\";s:16:\"pub_show_waysite\";s:5:\"param\";s:68:\"a:1:{s:8:\"template\";s:39:\"modules/waysite/templates_user/way.html\";}\";}}s:7:\"content\";a:3:{s:6:\"id_mod\";s:8:\"mapsite1\";s:9:\"id_action\";s:1:\"8\";s:3:\"run\";a:2:{s:4:\"name\";s:16:\"pub_show_mapsite\";s:5:\"param\";s:101:\"a:2:{s:13:\"id_page_start\";s:5:\"index\";s:8:\"template\";s:39:\"modules/mapsite/templates_user/map.html\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('catalog', 'index', 'Каталог товаров', '8', 'a:6:{s:7:\"caption\";s:29:\"Каталог товаров\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:29:\"Каталог товаров\";s:9:\"only_auth\";s:0:\"\";s:8:\"template\";s:21:\"design/template4.html\";s:15:\"link_other_page\";s:0:\"\";}', 'a:3:{s:5:\"title\";a:3:{s:6:\"id_mod\";s:8:\"catalog1\";s:9:\"id_action\";s:2:\"36\";s:3:\"run\";a:2:{s:4:\"name\";s:26:\"pub_catalog_show_item_name\";s:5:\"param\";s:252:\"a:2:{s:24:\"catalog_show_item_fields\";s:91:\"%manufacturer% %name% - отзывы, цены, доставка по всей России\";s:23:\"catalog_show_cat_fields\";s:76:\"%name% - отзывы, цены, доставка по всей России\";}\";}}s:8:\"content1\";a:3:{s:6:\"id_mod\";s:8:\"catalog1\";s:9:\"id_action\";s:2:\"30\";s:3:\"run\";a:2:{s:4:\"name\";s:21:\"pub_catalog_show_cats\";s:5:\"param\";s:326:\"a:6:{s:7:\"cat_tpl\";s:53:\"modules/catalog/templates_user//categories_santa.html\";s:33:\"catalog_categories_build_from_cat\";s:1:\"0\";s:35:\"catalog_categories_build_from_depth\";s:1:\"1\";s:35:\"catalog_categories_open_levels_show\";s:1:\"1\";s:34:\"catalog_categories_max_levels_show\";s:1:\"3\";s:22:\"catalog_items_pagename\";s:7:\"catalog\";}\";}}s:8:\"content2\";a:3:{s:6:\"id_mod\";s:8:\"catalog1\";s:9:\"id_action\";s:2:\"31\";s:3:\"run\";a:2:{s:4:\"name\";s:22:\"pub_catalog_show_items\";s:5:\"param\";s:254:\"a:4:{s:14:\"items_per_page\";s:2:\"20\";s:24:\"show_cats_if_empty_items\";s:4:\"true\";s:13:\"item_list_tpl\";s:57:\"modules/catalog/templates_user//catalog1_group1_list.html\";s:15:\"multi_group_tpl\";s:57:\"modules/catalog/templates_user//catalog1_group1_list.html\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('faq', 'index', 'Вопросы и ответы', '9', 'a:6:{s:7:\"caption\";s:30:\"Вопросы и ответы\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:30:\"Вопросы и ответы\";s:9:\"only_auth\";s:0:\"\";s:8:\"template\";s:21:\"design/template2.html\";s:15:\"link_other_page\";s:0:\"\";}', 'a:1:{s:7:\"content\";a:3:{s:6:\"id_mod\";s:4:\"faq1\";s:9:\"id_action\";s:2:\"25\";s:3:\"run\";a:2:{s:4:\"name\";s:7:\"pub_faq\";s:5:\"param\";s:37:\"a:1:{s:12:\"faq_ask_form\";s:4:\"true\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('news', 'index', 'Новости', '3', 'a:6:{s:7:\"caption\";s:14:\"Новости\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:14:\"Новости\";s:9:\"only_auth\";s:0:\"\";s:8:\"template\";s:21:\"design/template3.html\";s:15:\"link_other_page\";s:0:\"\";}', 'a:1:{s:8:\"content1\";a:3:{s:6:\"id_mod\";s:6:\"newsi1\";s:9:\"id_action\";s:2:\"16\";s:3:\"run\";a:2:{s:4:\"name\";s:16:\"pub_show_archive\";s:5:\"param\";s:172:\"a:5:{s:8:\"template\";s:40:\"modules/newsi/templates_user/arhive.html\";s:5:\"limit\";s:2:\"10\";s:4:\"type\";s:7:\"default\";s:10:\"pages_type\";s:5:\"block\";s:11:\"pages_count\";s:1:\"5\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('feedback', 'index', 'Обратная связь', '7', 'a:5:{s:7:\"caption\";s:27:\"Обратная связь\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:27:\"Обратная связь\";s:9:\"only_auth\";s:0:\"\";s:15:\"link_other_page\";s:0:\"\";}', 'a:1:{s:7:\"content\";a:3:{s:6:\"id_mod\";s:9:\"feedback1\";s:9:\"id_action\";s:2:\"24\";s:3:\"run\";a:2:{s:4:\"name\";s:13:\"pub_show_form\";s:5:\"param\";s:229:\"a:5:{s:8:\"template\";s:45:\"modules/feedback/templates_user/feedback.html\";s:5:\"email\";s:17:\"oslix@santafox.ru\";s:4:\"type\";s:4:\"html\";s:4:\"name\";s:5:\"Oslix\";s:5:\"theme\";s:53:\"Сообщение с сайта (etalon.santafox.ru)\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('search', 'index', 'Поиск', '2', 'a:9:{s:7:\"caption\";s:10:\"Поиск\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:10:\"Поиск\";s:9:\"only_auth\";s:0:\"\";s:8:\"template\";s:21:\"design/template2.html\";s:16:\"mapsite1_visible\";s:5:\"false\";s:16:\"waysite1_visible\";s:4:\"true\";s:13:\"menu1_visible\";s:5:\"false\";s:15:\"link_other_page\";s:0:\"\";}', 'a:1:{s:7:\"content\";a:3:{s:6:\"id_mod\";s:7:\"search1\";s:9:\"id_action\";s:2:\"35\";s:3:\"run\";a:2:{s:4:\"name\";s:23:\"pub_show_search_results\";s:5:\"param\";s:71:\"a:1:{s:8:\"template\";s:42:\"modules/search/templates_user//search.html\";}\";}}}');
INSERT INTO `%PREFIX%_structure` VALUES ('basket', 'index', 'Корзина', '10', 'a:9:{s:7:\"caption\";s:14:\"Корзина\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:14:\"Корзина\";s:9:\"only_auth\";b:0;s:8:\"template\";s:21:\"design/template4.html\";s:16:\"mapsite1_visible\";s:4:\"true\";s:16:\"waysite1_visible\";s:4:\"true\";s:13:\"menu1_visible\";s:5:\"false\";s:15:\"link_other_page\";s:0:\"\";}', 'a:2:{s:8:\"content1\";a:3:{s:6:\"id_mod\";s:8:\"catalog1\";s:9:\"id_action\";s:2:\"37\";s:3:\"run\";a:2:{s:4:\"name\";s:29:\"pub_catalog_show_basket_items\";s:5:\"param\";s:87:\"a:1:{s:16:\"basket_items_tpl\";s:49:\"modules/catalog/templates_user//basket_items.html\";}\";}}s:8:\"content2\";a:3:{s:6:\"id_mod\";s:0:\"\";s:9:\"id_action\";s:0:\"\";s:3:\"run\";s:0:\"\";}}');
INSERT INTO `%PREFIX%_structure` VALUES ('order', 'index', 'Страница заказа', '11', 'a:9:{s:7:\"caption\";s:29:\"Страница заказа\";s:11:\"title_other\";s:1:\"1\";s:10:\"name_title\";s:29:\"Страница заказа\";s:9:\"only_auth\";b:0;s:8:\"template\";s:21:\"design/template4.html\";s:16:\"mapsite1_visible\";s:5:\"false\";s:16:\"waysite1_visible\";s:5:\"false\";s:13:\"menu1_visible\";s:5:\"false\";s:15:\"link_other_page\";s:0:\"\";}', 'a:2:{s:8:\"content1\";a:3:{s:6:\"id_mod\";s:8:\"catalog1\";s:9:\"id_action\";s:2:\"39\";s:3:\"run\";a:2:{s:4:\"name\";s:34:\"pub_catalog_show_basket_order_form\";s:5:\"param\";s:523:\"a:6:{s:22:\"catalog_order_form_tpl\";s:49:\"modules/catalog/templates_user//basket_order.html\";s:30:\"catalog_order_manager_mail_tpl\";s:48:\"modules/catalog/templates_user//order_email.html\";s:31:\"catalog_order_manager_mail_subj\";s:36:\"Заказ на сайте %orderid%\";s:27:\"catalog_order_manager_email\";s:37:\"net_takogo_email@net_takogo_hosta.xxx\";s:19:\"order_user_mail_tpl\";s:48:\"modules/catalog/templates_user//order_email.html\";s:28:\"catalog_order_user_mail_subj\";s:46:\"Номер вашего заказа %orderid%\";}\";}}s:8:\"content2\";a:3:{s:6:\"id_mod\";s:0:\"\";s:9:\"id_action\";s:0:\"\";s:3:\"run\";s:0:\"\";}}');

