DROP TABLE IF EXISTS `%PREFIX%_stat_search`;
CREATE TABLE `%PREFIX%_stat_search` (
  `IDSearch` int(10) unsigned NOT NULL auto_increment,
  `search` varchar(32) NOT NULL default '',
  `preg_host` varchar(32) NOT NULL default '',
  `preg_word` varchar(32) NOT NULL default '',
  PRIMARY KEY  (`IDSearch`)
) ENGINE=MyISAM AUTO_INCREMENT=95 DEFAULT CHARSET=utf8 COMMENT='Статистика - поисковые системы';
INSERT INTO `%PREFIX%_stat_search` VALUES ('1','Yandex','ya(ndex)?\\.ru','(text|qs=text)');
INSERT INTO `%PREFIX%_stat_search` VALUES ('2','Aport','aport\\.ru','r=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('3','Rambler','rambler\\.ru','words=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('4','MetaBot','metabot\\.ru','st=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('5','Google (Images)','images\\.google\\.','(p|q)=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('6','Google','google\\.','(p|q)=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('7','MSN','msn\\.','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('8','Voila','voila\\.','kw=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('9','Yahoo','yahoo\\.','p=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('10','Lycos','lycos\\.','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('11','Alexa','alexa\\.com','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('12','AllTheWeb','alltheweb\\.com','q(|uery)=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('13','AltaVista','altavista\\.','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('14','DMOZ','dmoz\\.org','search=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('15','Netscape','netscape\\.','search=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('16','Terra','search\\.terra\\.','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('17','Search.com','www\\.search\\.com','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('18','AOL','search\\.aol\\.co','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('19','NorthernLight','northernlight\\.','qr=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('20','Hotbot','hotbot\\.','mt=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('21','Kvasir','kvasir\\.','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('22','MetaCrawler (Metamoteur)','metacrawler\\.','general=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('23','Go2Net (Metamoteur)','go2net\\.com','general=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('24','Go.com','(^|\\.)go\\.com','qt=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('25','Euroseek','euroseek\\.','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('26','Excite','excite\\.','search=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('27','Looksmart','looksmart\\.','key=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('28','Spray','spray\\.','string=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('29','NBCI','nbci\\.com\\/search','keyword=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('30','Ask Jeeves','(^|\\.)ask\\.com','ask=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('31','Atomz','atomz\\.','sp-q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('32','Overture','overture\\.com','keywords=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('33','Teoma','teoma\\.','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('34','Find Articles','findarticles\\.com','key=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('35','InfoSpace','infospace\\.com','qkw=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('36','Mamma','mamma\\.','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('37','Dogpile','dogpile\\.com','qkw=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('38','WISENut','wisenut\\.com','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('39','Earth Link','search\\.earthlink\\.net','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('40','Sympatico','search\\.sli\\.sympatico\\.ca','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('41','i-une.com','i-une\\.com','(keywords|q)=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('42','Cade','engine\\.exe','p1=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('43','Meta Miner','miner\\.bol\\.com\\.br','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('44','Baidu','baidu\\.com','word=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('45','Sina','search\\.sina\\.com','word=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('46','Sohu','search\\.sohu\\.com','word=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('47','Atlas.cz','atlas\\.cz','searchtext=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('48','Seznam.cz','seznam\\.cz','w=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('49','Centrum.cz','centrum\\.cz','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('50','Najdi.to','najdi\\.to','dotaz=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('51','Opasia','opasia\\.dk','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('52','Thor (danielsen.com)','danielsen\\.com','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('53','SOL','sol\\.dk','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('54','Jubii','jubii\\.dk','soegeord=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('55','Find','find\\.dk','words=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('56','Edderkoppen','edderkoppen\\.dk','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('57','Orbis','orbis\\.dk','search_field=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('58','1Klik','1klik\\.dk','query=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('59','Ofir','ofir\\.dk','querytext=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('60','Ilse','ilse\\.','search_for=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('61','Vindex','vindex\\.','in=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('62','Ask Jeeves UK','(^|\\.)ask\\.co\\.uk','ask=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('63','BBC','bbc\\.co\\.uk\\/cgi-bin\\/search','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('64','Freeserve','ifind\\.freeserve','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('65','Looksmart UK','looksmart\\.co\\.uk','key=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('66','Mirago','mirago\\.','txtsearch=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('67','Splut','splut\\.','pattern=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('68','Spotjockey','spotjockey\\.','Search_Keyword=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('69','UK Directory','ukdirectory\\.','k=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('70','UKIndex','ukindex\\.co\\.uk','stext=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('71','UK Plus','ukplus\\.','search=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('72','searchy.co.uk','searchy\\.co\\.uk','search_term=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('73','Ihmemaa','haku\\.www\\.fi','w=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('74','Francitй','francite\\.','name=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('75','Club-internet','recherche\\.club-internet\\.fr','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('76','Fireball','fireball\\.de','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('77','Infoseek','infoseek\\.de','qt=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('78','Abacho','suchen\\.abacho\\.de','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('79','T-Online','brisbane\\.t-online\\.de','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('80','Heureka','heureka\\.hu','heureka=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('81','Origo-Vizsla-Katalуgus','vizsla\\.origo\\.hu\\/katalogus?','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('82','Origo-Vizsla','vizsla\\.origo\\.hu','search=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('83','Startlapkeresх','lapkereso\\.hu','keres.php');
INSERT INTO `%PREFIX%_stat_search` VALUES ('84','Gуliбt','goliat\\.hu','KERESES=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('85','Index','index\\.hu','search.php3');
INSERT INTO `%PREFIX%_stat_search` VALUES ('86','Wahoo','wahoo\\.hu','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('87','FreeWeb','freeweb\\.hu','KERESES=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('88','Internetto Keresх','search\\.internetto\\.hu','searchstr=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('89','Virgilio','virgilio\\.it','qs=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('90','start.no','sok\\.start\\.no','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('91','Szukaj','szukaj\\.wp\\.pl','szukaj=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('92','Evreka','evreka\\.passagen\\.se','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('93','search.ch','search\\.ch','q=');
INSERT INTO `%PREFIX%_stat_search` VALUES ('94','search.bluewin.ch','search\\.bluewin\\.ch','qry=');
